# Generated by Django 3.2.8 on 2021-12-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
        ('mainapp', '0003_auto_20211215_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, related_name='features_for_product', to='specs.ProductFeatures', verbose_name='Характеристики'),
        ),
    ]
