# Generated by Django 3.2.8 on 2022-01-16 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0009_userproductrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='viewer',
            field=models.ManyToManyField(null=True, related_name='products', through='mainapp.UserProductRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
