# Generated by Django 3.2.8 on 2022-01-16 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specs', '0001_initial'),
        ('mainapp', '0010_auto_20220116_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='specs.ProductFeatures', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='viewer',
            field=models.ManyToManyField(related_name='products', through='mainapp.UserProductRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userproductrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], null=True),
        ),
    ]
