# Generated by Django 3.2.8 on 2022-01-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20220116_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='viewer',
            new_name='viewers',
        ),
    ]
